AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless XMEN-ADN 
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  AwsLambdaExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.projects.xmen_adn.StreamLambdaHandler::handleRequest
      Runtime: java21
      CodeUri: .
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  AwsLambdaExmenAdn:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: AwsLambdaExmenAdn
