package com.projects.xmen_adn.infrastructure.adapter.entityes;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@Builder
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "PERSONA")
public class PersonaEntity {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String personaId;

    @DynamoDBAttribute
    private String nombre;

    @DynamoDBAttribute
    private String apellido;

}
